kind: HelmChart
apiVersion: helm.cattle.io/v1
metadata:
  name: kube-ovn
  namespace: kube-system
spec:
  repo: https://kubeovn.github.io/kube-ovn/
  chart: kube-ovn
  version: "1.14.0"
  targetNamespace: kube-system
  valuesContent: |-
    # Auto-discover master nodes via label instead of static IPs
    MASTER_NODES: ""
    MASTER_NODES_LABEL: "kube-ovn/role=master"
    
    namespace: kube-system
    
    # Network stack and type
    networking:
      NET_STACK: ipv4
      ENABLE_SSL: false
      NETWORK_TYPE: geneve
      TUNNEL_TYPE: geneve
      IFACE: ""
      POD_NIC_TYPE: "veth-pair"
      EXCLUDE_IPS: ""
      EXCHANGE_LINK_NAME: false
      ENABLE_EIP_SNAT: true
      DEFAULT_SUBNET: "ovn-default"
      DEFAULT_VPC: "ovn-cluster"
      NODE_SUBNET: "join"
      ENABLE_ECMP: false
      ENABLE_METRICS: true
      NODE_LOCAL_DNS_IP: ""
      PROBE_INTERVAL: 180000
      OVN_NORTHD_PROBE_INTERVAL: 5000
      OVN_LEADER_PROBE_INTERVAL: 5
      OVN_REMOTE_PROBE_INTERVAL: 10000
      OVN_REMOTE_OPENFLOW_INTERVAL: 180
      OVN_NORTHD_N_THREADS: 1
      ENABLE_COMPACT: false
    
    # IPv4 network configuration
    ipv4:
      POD_CIDR: "10.42.0.0/16"
      POD_GATEWAY: "10.42.0.1"
      SVC_CIDR: "10.43.0.0/16"
      JOIN_CIDR: "10.64.0.0/16"
      PINGER_EXTERNAL_ADDRESS: "1.1.1.1"
      PINGER_EXTERNAL_DOMAIN: "kube-ovn.io."
    
    # Features - Network policies disabled for Cilium
    func:
      ENABLE_LB: true
      ENABLE_NP: false
      ENABLE_EXTERNAL_VPC: true
      HW_OFFLOAD: false
      ENABLE_LB_SVC: false
      ENABLE_KEEP_VM_IP: true
      LS_DNAT_MOD_DL_DST: true
      LS_CT_SKIP_DST_LPORT_IPS: true
      CHECK_GATEWAY: true
      LOGICAL_GATEWAY: false
      ENABLE_BIND_LOCAL_IP: true
      SECURE_SERVING: false
      ENABLE_NAT_GW: true
      ENABLE_OVN_IPSEC: false
      ENABLE_ANP: false
    
    # CNI configuration - Priority 10 for Cilium chaining
    cni_conf:
      CNI_CONFIG_PRIORITY: "10"
    
    # Image configuration
    global:
      registry:
        address: docker.io/kubeovn
        imagePullSecrets: []
      images:
        kubeovn:
          repository: kube-ovn
          vpcRepository: vpc-nat-gateway
          tag: v1.14.0
          support_arm: true
          thirdparty: true
    
    image:
      pullPolicy: IfNotPresent
