{
 "title": "Gossipsub Queues",
 "description": "Gossipsub Priority Queues ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({job=\"libp2p-nodes\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({job=\"libp2p-nodes\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "muxer",
    "label": "muxer",
    "query": {
     "query": "label_values({job=\"libp2p-nodes\"},muxer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delivery Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivery Delay (Per Peer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dst_testnode_last_message_delay_ms{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n  muxer=~\"$muxer\"\n}\nand on(namespace, pod, muxer)\n(\n  rate(dst_testnode_message_delay_ms_count{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    muxer=~\"$muxer\"\n  }[$__rate_interval]) > 0\n)",
       "legendFormat": "{{pod}} | {{muxer}}"
      }
     ]
    },
    {
     "title": "Max Delay",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max by (muxer) (\n  dst_testnode_last_message_delay_ms{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    muxer=~\"$muxer\"\n  }\n  and on(namespace, pod, muxer)\n  (\n    rate(dst_testnode_message_delay_ms_count{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\",\n      muxer=~\"$muxer\"\n    }[$__rate_interval]) > 0\n  )\n)",
       "legendFormat": "{{muxer}}"
      }
     ]
    },
    {
     "title": "Average Delay",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (muxer) (\n  dst_testnode_last_message_delay_ms{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    muxer=~\"$muxer\"\n  }\n  and on(namespace, pod, muxer)\n  (\n    rate(dst_testnode_message_delay_ms_count{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\",\n      muxer=~\"$muxer\"\n    }[$__rate_interval]) > 0\n  )\n)",
       "legendFormat": "{{muxer}}"
      }
     ]
    },
    {
     "title": "Delivery Delay P99",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (muxer, le) (\n    rate(dst_testnode_message_delay_ms_bucket{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\",\n      muxer=~\"$muxer\"\n    }[$__rate_interval])\n  )\n)",
       "legendFormat": "{{muxer}}"
      }
     ]
    },
    {
     "title": "P99 Delay",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "p99" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (muxer, le) (\n    rate(dst_testnode_message_delay_ms_bucket{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\",\n      muxer=~\"$muxer\"\n    }[$__rate_interval])\n  )\n)",
       "legendFormat": "{{muxer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Score & Penalty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Score",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 671 },
     "targets": [
      {
       "expr": "(libp2p_gossipsub_peers_scores{namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}  {{id}}"
      }
     ]
    },
    {
     "title": "Slow Peer Penalty Inc.",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 671 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\nincrease(libp2p_gossipsub_peers_score_slowPeerPenalty{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\"\n  })[$__rate_interval]\n",
       "legendFormat": "{{pod}} - SlowPeerPenalty Inc."
      }
     ]
    },
    {
     "title": "H/M/L Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 676 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "libp2p_gossipsub_medium_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}\n",
       "legendFormat": "{{pod}} Medium -> {{id}}"
      },
      {
       "expr": "libp2p_gossipsub_low_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}",
       "legendFormat": "{{pod}} - Low -> {{id}}"
      },
      {
       "expr": "libp2p_gossipsub_high_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}",
       "legendFormat": "{{pod}} - High -> {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Control Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "REBROADCAST SENT",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(libp2p_pubsub_messages_rebroadcasted_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})[$__rate_interval]",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "REBROADCAST",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(libp2p_pubsub_messages_rebroadcasted_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})[$__rate_interval]",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "DUPLICATE",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(libp2p_gossipsub_duplicate_total{namespace=~\"$namespace\", pod=~\"$pod\"})[$__rate_interval]",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "DUPLICATE COUNT",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(libp2p_gossipsub_duplicate_total{namespace=~\"$namespace\", pod=~\"$pod\"})[$__rate_interval]",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Number of received Graft",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 692 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_pubsub_received_graft_total{pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IHAVE Rate",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 7, "y": 692 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(libp2p_pubsub_received_ihave_total{namespace=~\"$namespace\", pod=~\"$pod\"})[$__rate_interval]",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "rate(\nlibp2p_pubsub_broadcast_ihave_total{namespace=~\"$namespace\", pod=~\"$pod\"})[$__rate_interval]",
       "legendFormat": "{{sent}}"
      }
     ]
    },
    {
     "title": "Gossip IWANT Received Inc.",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 692 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(libp2p_gossipsub_received_iwants{namespace=~\"$namespace\", pod=~\"$pod\"})[$__rate_interval]",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Pubsub IWANT Received Total",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 692 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "libp2p_pubsub_received_iwant_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Gossip IWANT Sent Inc.",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 696 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(libp2p_pubsub_broadcast_iwant_total{namespace=~\"$namespace\", pod=~\"$pod\"})[$__rate_interval]",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Gossip IWANT Sent Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 696 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(libp2p_pubsub_broadcast_iwant_total{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Low Priority Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Low Priority Queue Length vs Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(libp2p_gossipsub_low_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})\n",
       "legendFormat": "{{pod}} -> queue"
      },
      {
       "expr": "increase(libp2p_pubsub_low_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})[$__rate_interval]",
       "legendFormat": "{{pod}} - drop"
      }
     ]
    },
    {
     "title": "Low Priority Queue Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(libp2p_pubsub_low_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})[$__rate_interval]",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Slow Peer Penalty Inc. vs DROP [LOW]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\nincrease(libp2p_gossipsub_peers_score_slowPeerPenalty{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\"\n  })[$__rate_interval]\n",
       "legendFormat": "{{pod}} - SlowPeerPenalty Inc."
      },
      {
       "expr": "increase(libp2p_pubsub_low_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})[$__rate_interval]",
       "legendFormat": "{{pod}} - LOW DROP Inc."
      }
     ]
    },
    {
     "title": "IHAVE RECEIVED RATE vs LOW DROP",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(libp2p_pubsub_received_ihave_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - IHAVE RX"
      },
      {
       "expr": "rate(libp2p_pubsub_low_priority_queue_drops_total{namespace=~\"$namespace\", pod=\"nimp2p-1\"}[1m])",
       "legendFormat": "{{pod}} - Low -Drop"
      }
     ]
    },
    {
     "title": "Low Priority Queue Drop Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_pubsub_low_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}",
       "legendFormat": "{{pod}} - Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Medium Priority Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Medium Priority Queue Length vs Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "libp2p_gossipsub_medium_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}\n",
       "legendFormat": "{{pod}} - Queue"
      },
      {
       "expr": "increase(libp2p_pubsub_medium_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})[$__rate_interval]",
       "legendFormat": "{{pod}} - Drop"
      }
     ]
    },
    {
     "title": "Medium Priority Queue Drop Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(libp2p_pubsub_medium_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n}[$__rate_interval])\n",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Slow Peer Penalty Inc. vs DROP [Medium]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\nincrease(libp2p_gossipsub_peers_score_slowPeerPenalty{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\"\n  })[$__rate_interval]\n",
       "legendFormat": "{{pod}} - SlowPeerPenalty Inc."
      },
      {
       "expr": "increase(libp2p_pubsub_medium_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})[$__rate_interval]",
       "legendFormat": "{{pod}} - Medium DROP Inc."
      }
     ]
    },
    {
     "title": "Medium Priority Queue Drop Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_pubsub_medium_priority_queue_drops_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}",
       "legendFormat": "{{pod}} - Total"
      }
     ]
    }
   ]
  },
  {
   "title": "High Priority Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "High Priority Disconnect",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "(libp2p_pubsub_disconnects_over_high_priority_queue_limit_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})",
       "legendFormat": "{{pod}} - High - disconnect"
      },
      {
       "expr": "(libp2p_pubsub_high_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "High Priority Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "libp2p_gossipsub_high_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n}\n",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "High Priority Disconnect",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(libp2p_pubsub_disconnects_over_high_priority_queue_limit_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})",
       "legendFormat": "{{pod}} - High - disconnect"
      },
      {
       "expr": "(libp2p_pubsub_high_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "(libp2p_peers{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})",
       "legendFormat": "{{pod}} - High - disconnect"
      },
      {
       "expr": "(libp2p_pubsub_high_priority_queue_size{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\",\n})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Rate & Publisher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Rate TX",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n}[$__rate_interval])*8\n",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Number of Publishe messages",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 283 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(muxer)(dst_testnode_completed_messages_total_total{namespace=~\"$namespace\",muxer=~\"$muxer\",pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data Rate RX",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 289 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n}[$__rate_interval])*8\n",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Number of Publishe messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 289 },
     "targets": [
      {
       "expr": "(dst_testnode_completed_messages_total_total{namespace=~\"$namespace\",muxer=~\"$muxer\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup (From Log)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "direction": "desc",
       "expr": "kubernetes.pod_namespace:\"libp2p-lab\" AND _msg:\"milliseconds\"\n| extract \"milliseconds: <latency>\"\n| stats by (_time:1ms) max(latency) as latency\n| sort by (_time desc)"
      }
     ]
    }
   ]
  }
 ]
}