{
 "title": "Network",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "protocol",
    "label": "protocol",
    "query": {
     "query": "label_values(iperf_throughput_bps,protocol)"
    }
   },
   {
    "name": "source",
    "label": "source",
    "query": {
     "query": "label_values(iperf_throughput_bps,src)"
    }
   }
  ]
 },
 "panels": [
  { "title": "QUICK STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Nework UL Health (%)",
   "type": "bargauge",
   "description": "Observed Throughput over 20 Gbps. 100% means the observed Throughput is 20 Gbps",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n\n      last_over_time(iperf_throughput_bps{protocol=\"tcp\", direction=\"UL\", mode=\"pod_network\"}[$__range]) / 20e9\n    \n",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Pod Nework DL Health (%)",
   "type": "bargauge",
   "description": "Observed Throughput over 20 Gbps. 100% means the observed Throughput is 20 Gbps",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(iperf_throughput_bps{protocol=\"tcp\", direction=\"DL\", mode=\"pod_network\"}[$__range]) / 20e9\n    \n",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Pod Nework RTT Health (<= 1ms)",
   "type": "bargauge",
   "description": "Observed Min RTT compared to baseline 1ms.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nlast_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"pod_network\",stat=\"min\"}[$__range])\n    \n",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  { "title": "LATEST POD NETWORK THROUGHPUT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod Nework UL Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  iperf_throughput_bps{protocol=~\"$protocol\", direction=\"UL\", mode=\"pod_network\"}[$__range]\n)",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "UL TCP Retransmissions",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(iperf_retransmits_total{protocol=\"tcp\",direction=\"UL\",mode=\"pod_network\"}[$__range])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "UL CWD AVG",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(iperf_tcp_avg_cwnd_bytes{protocol=\"tcp\",direction=\"UL\",mode=\"pod_network\"})[$__range]",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "UL RTT MIN",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"pod_network\",stat=\"min\"}[$__range])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "UL RTT AVG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"pod_network\",stat=\"avg\"}[$__range])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Pod Nework DL Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(iperf_throughput_bps{protocol=~\"$protocol\",direction=\"DL\",mode=\"pod_network\"}[$__range])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "DL TCP Retransmissions",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(iperf_retransmits_total{protocol=\"tcp\",direction=\"DL\",mode=\"pod_network\"}[$__range])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "UL RTT MAX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"pod_network\",stat=\"max\"}[$__range])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "LATEST HOSTNETWORK / THROUGHPUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "HostNework UL Throughput",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(\n  iperf_throughput_bps{protocol=~\"$protocol\", direction=\"UL\", mode=\"host_network\"}[$__range]\n)",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "UL TCP Retransmissions",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(iperf_retransmits_total{protocol=\"tcp\",direction=\"UL\",mode=\"host_network\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "UL CWD AVG",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(iperf_tcp_avg_cwnd_bytes{protocol=\"tcp\",direction=\"UL\",mode=\"host_network\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "UL RTT MIN",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "last_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"host_network\",stat=\"min\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "UL RTT AVG",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "last_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"host_network\",stat=\"avg\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "HostNework DL Throughput",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(iperf_throughput_bps{protocol=~\"$protocol\",direction=\"DL\",mode=\"host_network\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "DL TCP Retransmissions",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 11, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(iperf_retransmits_total{protocol=\"tcp\",direction=\"DL\",mode=\"host_network\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    },
    {
     "title": "UL RTT MAX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "last_over_time(iperf_rtt_ms{protocol=\"tcp\",direction=\"UL\",mode=\"host_network\",stat=\"max\"}[$__range])",
       "legendFormat": "{{dest}}"
      }
     ]
    }
   ]
  }
 ]
}