{
 "title": "Node Hardware",
 "description": "Node Hardware Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "hostname",
    "query": {
     "query": "label_values({job=\"node-exporter\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TEMPERATURE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "description": "All CPU cores Temperature",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "device_id",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (nodename, chip_name) (\n  (\n    node_hwmon_temp_celsius{job=\"node-exporter\"}\n    * on(instance, chip) group_left(chip_name)\n      node_hwmon_chip_names{\n        job=\"node-exporter\",\n        chip_name=~\".*(coretemp|k10temp|zenpower).*\"\n      }\n  )\n  * on(instance) group_left(nodename)\n    node_uname_info{nodename=~\"$host\", job=\"node-exporter\"}\n)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "NIC TEMPERATURE",
   "type": "timeseries",
   "description": "Network Interface Card Temperature",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (nodename, chip_name) (\n  (\n    node_hwmon_temp_celsius{job=\"node-exporter\"}\n    * on(instance, chip) group_left(chip_name)\n      node_hwmon_chip_names{\n        job=\"node-exporter\",\n        chip_name=~\"i350bb|mlx5\"\n      }\n  )\n  * on(instance) group_left(nodename)\n    node_uname_info{nodename=~\"$host\", job=\"node-exporter\"}\n)",
     "legendFormat": "{{nodename}}-{{chip_name}}"
    }
   ]
  },
  {
   "title": "NVME TEMPERATURE",
   "type": "stat",
   "description": "Disk Temperature",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (nodename, chip_name) (\n  (\n    node_hwmon_temp_celsius{job=\"node-exporter\"}\n    * on(instance, chip) group_left(chip_name)\n      node_hwmon_chip_names{\n        job=\"node-exporter\",\n        chip_name=~\".*nvme.*\"\n      }\n  )\n  * on(instance) group_left(nodename)\n    node_uname_info{nodename=~\"$host\", job=\"node-exporter\"}\n)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } }
 ]
}