{
 "title": "local nimlibp2p",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "LibP2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "{{instance}}-Top5" }
   ]
  },
  {
   "title": "Libp2p Open Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_open_streams",
     "legendFormat": "{{instance}}-{{type}}-{{dir}}-Top5"
    }
   ]
  },
  {
   "title": "libp2p traffic - In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}-Top5"
    }
   ]
  },
  {
   "title": "libp2p traffic - Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}-Top5"
    }
   ]
  },
  {
   "title": "Nim GC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nim_gc_mem_bytes", "legendFormat": "{{instance}}-Top5" }
   ]
  },
  {
   "title": "Container RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "{{pod}}-{{node}}-Top5" }
   ]
  },
  {
   "title": "libp2p unhealthy peers (d_low)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (libp2p_gossipsub_low_peers_topics)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}