{
 "title": "nimlibp2p-vacdst",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "libp2p_traffic_in_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_in_bot5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_bot5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "nim_gc_mem_bytes_top5",
    "query": {
     "query": "query_result(topk(5, nim_gc_mem_bytes))"
    }
   },
   {
    "name": "nim_gc_mem_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, nim_gc_mem_bytes))"
    }
   },
   {
    "name": "container_memory_usage_bytes_top5",
    "query": {
     "query": "query_result(topk(5, rate(container_memory_usage_bytes{namespace=\"zerotesting-dst\"}[${__range_s}s])))"
    }
   },
   {
    "name": "container_memory_usage_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(container_memory_usage_bytes{namespace=\"zerotesting-dst\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_open_streams_top5",
    "query": {
     "query": "query_result(topk(5, libp2p_open_streams))"
    }
   },
   {
    "name": "libp2p_open_streams_bottom5",
    "query": {
     "query": "query_result(bottomk(5, libp2p_open_streams))"
    }
   },
   {
    "name": "libp2p_peers_top5",
    "query": {
     "query": "query_result(topk(5, libp2p_peers))"
    }
   },
   {
    "name": "libp2p_peers_bottom5",
    "query": {
     "query": "query_result(bottomk(5, libp2p_peers))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LibP2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_peers{namespace=\"zerotesting-dst\", instance=~\"$libp2p_peers_top5\"}",
     "legendFormat": "{{instance}}-Top5"
    },
    {
     "expr": "libp2p_peers{namespace=\"zerotesting-dst\", instance=~\"$libp2p_peers_bottom5\"}",
     "legendFormat": "{{instance}}-Bot5"
    }
   ]
  },
  {
   "title": "Libp2p Open Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_open_streams{namespace=\"zerotesting-dst\", instance=~\"$libp2p_open_streams_top5\"}",
     "legendFormat": "{{instance}}-{{type}}-{{dir}}-Top5"
    },
    {
     "expr": "libp2p_open_streams{namespace=\"zerotesting-dst\", instance=~\"$libp2p_open_streams_bottom5\"}",
     "legendFormat": "{{instance}}-{{type}}-{{dir}}-Bot5"
    }
   ]
  },
  {
   "title": "libp2p traffic - In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\", instance=~\"$libp2p_traffic_in_top5\", namespace=\"zerotesting-dst\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}-Top5"
    },
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\", instance=~\"$libp2p_traffic_in_bot5\", namespace=\"zerotesting-dst\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}-Bot5"
    }
   ]
  },
  {
   "title": "libp2p traffic - Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\", instance=~\"$libp2p_traffic_out_top5\", namespace=\"zerotesting-dst\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}-Top5"
    },
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\", instance=~\"$libp2p_traffic_out_bot5\", namespace=\"zerotesting-dst\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}-Bot5"
    }
   ]
  },
  {
   "title": "Nim GC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{namespace=\"zerotesting-dst\", instance=~\"$nim_gc_mem_bytes_top5\"}",
     "legendFormat": "{{instance}}-Top5"
    },
    {
     "expr": "nim_gc_mem_bytes{namespace=\"zerotesting-dst\", instance=~\"$nim_gc_mem_bytes_bottom5\"}",
     "legendFormat": "{{instance}}-Bot5"
    }
   ]
  },
  {
   "title": "Container RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"zerotesting-dst\", pod=~\"$container_memory_usage_bytes_top5\"}",
     "legendFormat": "{{pod}}-{{node}}-Top5"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"zerotesting-dst\", pod=~\"$container_memory_usage_bytes_bottom5\"}",
     "legendFormat": "{{pod}}-{{node}}-Bot5"
    }
   ]
  },
  {
   "title": "libp2p low peers topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (libp2p_gossipsub_low_peers_topics{namespace=\"zerotesting-dst\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "libp2p healthy peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (libp2p_gossipsub_healthy_peers_topics{namespace=\"zerotesting-dst\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}