{
 "title": "Nomos Consumption",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"vaclab\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  max by (pod, container) (\n    rate(\n      container_cpu_usage_seconds_total{\n        namespace=~\"$namespace\",\n        container!=\"\",\n        container!=\"POD\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory working set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  max by (pod, container) (\n    container_memory_working_set_bytes{\n      namespace=~\"$namespace\",\n      container!=\"\",\n      container!=\"POD\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "consensus_forks_count", "legendFormat": "{{service_name}}" }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  max by (pod, container) (\n    container_memory_rss{\n      namespace=~\"$namespace\",\n      container!=\"\",\n      container!=\"POD\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  max by (pod, container) (\n    container_memory_cache{\n      namespace=~\"$namespace\",\n      container!=\"\",\n      container!=\"POD\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blend connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "blend_peers_connected", "legendFormat": "{{service_name}}" }
   ]
  }
 ]
}