{
 "title": "nWaku Raw Bandwidth",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "libp2p_peers_top5",
    "query": {
     "query": "query_result(topk(5, libp2p_peers))"
    }
   },
   {
    "name": "libp2p_peers_bottom5",
    "query": {
     "query": "query_result(bottomk(5, libp2p_peers))"
    }
   },
   {
    "name": "libp2p_traffic_in_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_in_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_open_streams_top5",
    "query": {
     "query": "query_result(topk(5, libp2p_open_streams))"
    }
   },
   {
    "name": "libp2p_open_streams_bottom5",
    "query": {
     "query": "query_result(bottomk(5, libp2p_open_streams))"
    }
   },
   {
    "name": "container_network_receive_top5",
    "query": {
     "query": "query_result(topk(5,   rate(container_network_receive_bytes_total{namespace=\"zerotesting\"}[${__range_s}s])  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod)))"
    }
   },
   {
    "name": "container_network_receive_bottom5",
    "query": {
     "query": "query_result(bottomk(5,   rate(container_network_receive_bytes_total{namespace=\"zerotesting\"}[${__range_s}s])  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod)))"
    }
   },
   {
    "name": "container_network_transmit_top5",
    "query": {
     "query": "query_result(topk(5, rate(container_network_transmit_bytes_total{namespace=\"zerotesting\"}[${__range_s}s]))  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod)))"
    }
   },
   {
    "name": "container_network_transmit_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(container_network_transmit_bytes_total{namespace=\"zerotesting\"}[${__range_s}s]))  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod))"
    }
   },
   {
    "name": "container_memory_usage_bytes_top5",
    "query": {
     "query": "query_result(topk(5, rate(container_memory_usage_bytes{namespace=\"zerotesting\"}[${__range_s}s])))"
    }
   },
   {
    "name": "container_memory_usage_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(container_memory_usage_bytes{namespace=\"zerotesting\"}[${__range_s}s])))"
    }
   },
   {
    "name": "nim_gc_mem_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, nim_gc_mem_bytes))"
    }
   },
   {
    "name": "nim_gc_mem_bytes_top5",
    "query": {
     "query": "query_result(topk(5, nim_gc_mem_bytes))"
    }
   },
   {
    "name": "discv5_in_top5",
    "query": {
     "query": "query_result(topk(5, rate(discv5_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "discv5_in_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(discv5_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "discv5_out_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(discv5_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "discv5_out_top5",
    "query": {
     "query": "query_result(topk(5, rate(discv5_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "LibP2P bytes per second (in)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_bytes_in_total_port_60000_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P bytes per second (out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_bytes_out_total_port_60000_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DiscV5 bytes per second (in)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_bytes_in_total_port_9000_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DiscV5 bytes per second (out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_bytes_out_total_port_9000_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Bandwidth (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_receive_top5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}}-Top"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_receive_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}} (Bottom)"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_transmit_top5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}}-Top"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_transmit_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}}-Bottom"
    }
   ]
  }
 ]
}