{
 "title": "Internal - MIX testnet 0.2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({job=\"mix-testnet-0.2\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({job=\"libp2p-nodes\", namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mix Received / Forwarded", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mix Received Message Total (ALL)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mix_messages_recvd_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix Forwarded Message Total",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mix_messages_forwarded_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix Received Message Total (By Type)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type)(increase(mix_messages_recvd_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix Forwarded Message Total (By Type)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type)(increase(mix_messages_forwarded_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix Received Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(mix_messages_recvd_total{namespace=~\"$namespace\",instance=~\"$pod\"\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mix Forwarded Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(mix_messages_forwarded_total{namespace=~\"$namespace\",instance=~\"$pod\"\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mix Forwarded Message (over time)",
   "type": "timeseries",
   "description": "Include all messages types",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(mix_messages_forwarded_total{namespace=~\"$namespace\",instance=~\"$pod\"\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mix Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Increase Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (error) (increase(mix_messages_error_total{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Total By Category",
     "type": "stat",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (error)(increase(mix_messages_error_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Total ALL",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (increase(mix_messages_error_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Mix Cover Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cover Message Total",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((mix_cover_received_total{namespace=~\"$namespace\", instance=~\"$pod\"}))\n\n",
       "legendFormat": "Received"
      },
      {
       "expr": "sum((mix_cover_emitted_total{namespace=~\"$namespace\", instance=~\"$pod\"}))\n",
       "legendFormat": "Emitted"
      },
      {
       "expr": "sum((mix_cover_precomputed_total{namespace=~\"$namespace\", instance=~\"$pod\"}))\n",
       "legendFormat": "Precomputed"
      },
      {
       "expr": "sum((mix_cover_error_total{namespace=~\"$namespace\", instance=~\"$pod\"}))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Cover Traffic Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(mix_cover_received_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__rate_interval]))\n\n",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(mix_cover_emitted_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__rate_interval]))\n",
       "legendFormat": "Emitted"
      },
      {
       "expr": "sum(rate(mix_cover_precomputed_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__rate_interval]))\n",
       "legendFormat": "Precomputed"
      },
      {
       "expr": "sum(rate(mix_cover_error_total{namespace=~\"$namespace\", instance=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Rate TX",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(sum by (pod)(container_network_transmit_bytes_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})[$__rate_interval])*8\n",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Data Rate RX",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(sum by (pod)(container_network_receive_bytes_total{\n  namespace=~\"$namespace\",\n  pod=~\"$pod\"\n})[$__rate_interval])*8\n",
       "legendFormat": "{{pod}} "
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\",image!=\"\",container!=\"\"}) by(pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\",image!=\"\",container!=\"\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "RLN Proof Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Proof Generation Duration Histogram",
   "type": "histogram",
   "description": "per node histogram can be obtained by setting pod selector to a target node instead of All",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(mix_rln_proof_generation_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le,mode))",
     "legendFormat": "p50 ({{mode}}) "
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mix_rln_proof_generation_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le,mode))",
     "legendFormat": "p95 ({{mode}}) "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mix_rln_proof_generation_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le, mode))",
     "legendFormat": "p99 ({{mode}}) "
    }
   ]
  },
  {
   "title": "Avgerage Proof Generation Duration (Over Time)",
   "type": "timeseries",
   "description": "SUM/COUNT",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mix_rln_proof_generation_duration_seconds_sum{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (instance)\n/\nsum(rate(mix_rln_proof_generation_duration_seconds_count{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Generation Duration p95",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(mix_rln_proof_generation_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le, instance)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RLN Proof Verification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Proof Verification Duration Histogram",
   "type": "histogram",
   "description": "per node histogram can be obtained by setting pod selector to a target node instead of All",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(mix_rln_proof_verification_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mix_rln_proof_verification_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mix_rln_proof_verification_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Avgerage Proof Verification Duration (Over Time)",
   "type": "timeseries",
   "description": "SUM/COUNT",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mix_rln_proof_verification_duration_seconds_sum{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (instance)\n/\nsum(rate(mix_rln_proof_verification_duration_seconds_count{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Verification Duration p95",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(mix_rln_proof_verification_duration_seconds_bucket{namespace=~\"$namespace\",instance=~\"$pod\"}[$__rate_interval])) by (le, instance)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}