{
 "title": "External Blockchain Nodes",
 "tags": [ "public" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "consensus_connections{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Consensus peers connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "consensus_peers_connected{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Tip Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_tip_height{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Finalized Height (LIB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_finalized_height{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Consensus forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "consensus_forks_count{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Tip poll triggered total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "tip_poll_triggered_total{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Blend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Message Flow Rate — events/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "msgps" } },
   "targets": [
    {
     "expr": "rate(blend_messages_sent_total{namespace=\"\"}[5m])",
     "legendFormat": "Sent/sec - {{service_name}}"
    }
   ]
  },
  {
   "title": "Blend connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "blend_peers_connected{namespace=\"\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}