apiVersion: v1
kind: ConfigMap
metadata:
  name: vaclab-ntp-server-conf
data:
  chrony.conf: |
    server consolidare-continuum.com iburst
    server time.cloudflare.com iburst
    driftfile /var/lib/chrony/drift
    rtcsync
    makestep 1.0 3
    local stratum 10
    allow 185.181.228.0/24
    allow 65.21.76.50/32
    allow 10.42.0.0/16
    allow 10.43.0.0/16
    logdir /var/log/chrony