apiVersion: v1
kind: Service
metadata:
  name: hubble-relay-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium
spec:
  type: NodePort
  selector:
    k8s-app: hubble-relay
  ports:
  - name: grpc
    protocol: TCP
    port: 4245
    targetPort: 4245
    nodePort: 31245
