apiVersion: v1
kind: Service
metadata:
  name: otlp-collector-external
  namespace: opentelemetry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: otel
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  ports:
  - name: grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
    nodePort: 31317
  - name: http
    protocol: TCP
    port: 4318
    targetPort: 4318
    nodePort: 31318
