apiVersion: v1
kind: Service
metadata:
  name: ntp-server-nodeport
spec:
  type: NodePort
  selector:
    app: ntp-server
  ports:
    - name: ntp
      protocol: UDP
      port: 123
      targetPort: 123
      nodePort: 30123
