apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  00-google-source.yaml: |
    version: 1
    metadata:
      name: google-source
    entries:
      - model: authentik_sources_oauth.oauthsource
        id: google
        identifiers:
          name: Google
        attrs:
          name: Google
          slug: google
          provider_type: google
          consumer_key: !Env GOOGLE_CLIENT_ID
          consumer_secret: !Env GOOGLE_CLIENT_SECRET
          authentication_flow: !Find [authentik_flows.flow, [slug, "default-source-authentication"]]
          enrollment_flow: !Find [authentik_flows.flow, [slug, "default-source-enrollment"]]
      
      # Link Google source to the default authentication flow's identification stage
      - model: authentik_stages_identification.identificationstage
        identifiers:
          name: default-authentication-identification
        attrs:
          sources:
            - !KeyOf google
  
  01-keycloak-source.yaml: |
    version: 1
    metadata:
      name: keycloak-source
    entries:
      - model: authentik_sources_oauth.oauthsource
        id: keycloak
        identifiers:
          name: Keycloak
        attrs:
          name: Keycloak
          slug: keycloak
          provider_type: openidconnect
          consumer_key: !Env KEYCLOAK_CLIENT_ID
          consumer_secret: !Env KEYCLOAK_CLIENT_SECRET
          oidc_well_known_url: !Env KEYCLOAK_WELL_KNOWN_URL
          authentication_flow: !Find [authentik_flows.flow, [slug, "default-source-authentication"]]
          enrollment_flow: !Find [authentik_flows.flow, [slug, "default-source-enrollment"]]
  10-proxy-forwardauth-with-outpost.yaml: |
    version: 1
    metadata:
      name: proxy-forwardauth-with-outpost
    entries:
      # 1. Proxy provider for forward auth (forward_single mode)
      - model: authentik_providers_proxy.proxyprovider
        id: k8s-forwardauth-provider
        identifiers:
          name: k8s-forwardauth
        attrs:
          name: k8s-forwardauth
          mode: forward_single
          internal_host: ""
          external_host: https://authentik.lab.vac.dev
          cookie_domain: lab.vac.dev
          authorization_flow: !Find [authentik_flows.flow, [slug, "default-provider-authorization-implicit-consent"]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, "default-provider-invalidation-flow"]]

      # 2. Single application for forward auth (protects all ingresses with the middleware)
      - model: authentik_core.application
        identifiers:
          slug: k8s-forwardauth
        attrs:
          name: "K8s ForwardAuth"
          slug: "k8s-forwardauth"
          provider: !KeyOf k8s-forwardauth-provider
          meta_launch_url: "https://auth.lab.vac.dev"
  
  20-outpost.yaml: |
    version: 1
    metadata:
      name: k8s-outpost
    entries:
      # Assign the k8s-forwardauth provider to the embedded outpost
      - model: authentik_outposts.outpost
        identifiers:
          name: "authentik Embedded Outpost"
        attrs:
          providers:
            - !Find [authentik_providers_proxy.proxyprovider, [name, "k8s-forwardauth"]]

  
  30-grafana-oidc.yaml: |
    version: 1
    metadata:
      name: grafana-oidc
    entries:
      # Fix openid scope to include sub claim (required by OIDC spec)
      - model: authentik_providers_oauth2.scopemapping
        identifiers:
          scope_name: openid
        attrs:
          scope_name: openid
          name: "authentik default OAuth Mapping: OpenID 'openid'"
          description: "OpenID scope with sub claim"
          expression: |
            # The sub claim is required by OIDC spec
            return {
              "sub": str(request.user.pk),
            }
      
      # Custom scope mapping for Grafana compatibility
      - model: authentik_providers_oauth2.scopemapping
        id: grafana-scope
        identifiers:
          name: Grafana Scope Mapping
        attrs:
          name: Grafana Scope Mapping
          scope_name: profile
          description: "Profile scope with login claim for Grafana"
          expression: |
            return {
              "name": request.user.name,
              "given_name": request.user.name,
              "preferred_username": request.user.username,
              "nickname": request.user.username,
              "login": request.user.username,
              "groups": [group.name for group in request.user.ak_groups.all()],
            }
      
      - model: authentik_providers_oauth2.oauth2provider
        id: grafana-provider
        identifiers:
          name: grafana
        attrs:
          name: grafana
          client_id: !Env GRAFANA_OIDC_CLIENT_ID
          client_secret: !Env GRAFANA_OIDC_CLIENT_SECRET
          redirect_uris:
            - matching_mode: strict
              url: "https://grafana.lab.vac.dev/login/generic_oauth"
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
          authorization_flow: !Find [authentik_flows.flow, [slug, "default-provider-authorization-explicit-consent"]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, "default-provider-invalidation-flow"]]
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "openid"]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "email"]]
            - !KeyOf grafana-scope

      - model: authentik_core.application
        id: grafana-app
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          slug: grafana
          provider: !KeyOf grafana-provider
  
  40-rancher-oidc.yaml: |
    version: 1
    metadata:
      name: rancher-oidc
    entries:
      # Custom scope mapping for Rancher groups
      - model: authentik_providers_oauth2.scopemapping
        id: rancher-groups-scope
        identifiers:
          name: Rancher Groups Mapping
        attrs:
          name: Rancher Groups Mapping
          scope_name: profile
          description: "Profile scope with groups for Rancher"
          expression: |
            return {
              "name": request.user.name,
              "given_name": request.user.name,
              "preferred_username": request.user.username,
              "nickname": request.user.username,
              "email": request.user.email,
              "groups": [group.name for group in request.user.ak_groups.all()],
            }
      
      - model: authentik_providers_oauth2.oauth2provider
        id: rancher-provider
        identifiers:
          name: rancher
        attrs:
          name: rancher
          client_id: !Env RANCHER_OIDC_CLIENT_ID
          client_secret: !Env RANCHER_OIDC_CLIENT_SECRET
          redirect_uris:
            - matching_mode: strict
              url: "https://rancher.lab.vac.dev/verify-auth"
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
          authorization_flow: !Find [authentik_flows.flow, [slug, "default-provider-authorization-explicit-consent"]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, "default-provider-invalidation-flow"]]
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "openid"]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "email"]]
            - !KeyOf rancher-groups-scope

      - model: authentik_core.application
        id: rancher-app
        identifiers:
          slug: rancher
        attrs:
          name: Rancher
          slug: rancher
          provider: !KeyOf rancher-provider
