{
 "title": "nimlibp2p-vacp2p",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container_memory_usage_bytes_top5",
    "query": {
     "query": "query_result(topk(5, rate(container_memory_usage_bytes{namespace=\"p2p-team\"}[${__range_s}s])))"
    }
   },
   {
    "name": "container_memory_usage_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(container_memory_usage_bytes{namespace=\"p2p-team\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_in_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_in_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "libp2p traffic - In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\", namespace=\"p2p-team\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "libp2p traffic - Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\", namespace=\"p2p-team\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"p2p-team\", container=\"container-0\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}