{
 "title": "nWaku",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "libp2p_peers_top5",
    "query": {
     "query": "query_result(topk(5, libp2p_peers))"
    }
   },
   {
    "name": "libp2p_peers_bottom5",
    "query": {
     "query": "query_result(bottomk(5, libp2p_peers))"
    }
   },
   {
    "name": "libp2p_traffic_in_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_in_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_top5",
    "query": {
     "query": "query_result(topk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_traffic_out_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(libp2p_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "libp2p_open_streams_top5",
    "query": {
     "query": "query_result(topk(5, libp2p_open_streams))"
    }
   },
   {
    "name": "libp2p_open_streams_bottom5",
    "query": {
     "query": "query_result(bottomk(5, libp2p_open_streams))"
    }
   },
   {
    "name": "container_network_receive_top5",
    "query": {
     "query": "query_result(topk(5,   rate(container_network_receive_bytes_total{namespace=\"zerotesting\"}[${__range_s}s])  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod)))"
    }
   },
   {
    "name": "container_network_receive_bottom5",
    "query": {
     "query": "query_result(bottomk(5,   rate(container_network_receive_bytes_total{namespace=\"zerotesting\"}[${__range_s}s])  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod)))"
    }
   },
   {
    "name": "container_network_transmit_top5",
    "query": {
     "query": "query_result(topk(5, rate(container_network_transmit_bytes_total{namespace=\"zerotesting\"}[${__range_s}s]))  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod)))"
    }
   },
   {
    "name": "container_network_transmit_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(container_network_transmit_bytes_total{namespace=\"zerotesting\"}[${__range_s}s]))  * on(pod) group_left()  sum(kube_pod_container_status_running{}) by (pod))"
    }
   },
   {
    "name": "container_memory_usage_bytes_top5",
    "query": {
     "query": "query_result(topk(5, rate(container_memory_usage_bytes{namespace=\"zerotesting\"}[${__range_s}s])))"
    }
   },
   {
    "name": "container_memory_usage_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(container_memory_usage_bytes{namespace=\"zerotesting\"}[${__range_s}s])))"
    }
   },
   {
    "name": "nim_gc_mem_bytes_bottom5",
    "query": {
     "query": "query_result(bottomk(5, nim_gc_mem_bytes))"
    }
   },
   {
    "name": "nim_gc_mem_bytes_top5",
    "query": {
     "query": "query_result(topk(5, nim_gc_mem_bytes))"
    }
   },
   {
    "name": "discv5_in_top5",
    "query": {
     "query": "query_result(topk(5, rate(discv5_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "discv5_in_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(discv5_network_bytes_total{direction=\"in\"}[${__range_s}s])))"
    }
   },
   {
    "name": "discv5_out_bottom5",
    "query": {
     "query": "query_result(bottomk(5, rate(discv5_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   {
    "name": "discv5_out_top5",
    "query": {
     "query": "query_result(topk(5, rate(discv5_network_bytes_total{direction=\"out\"}[${__range_s}s])))"
    }
   },
   { "name": "query0" },
   {
    "name": "top_discv5_discovered",
    "query": {
     "query": "query_result(topk(5, rate(waku_discv5_discovered[${__range_s}s])))"
    }
   },
   {
    "name": "bottom_discv5_discovered",
    "query": {
     "query": "query_result(bottomk(5, rate(waku_discv5_discovered[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LibP2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_peers{instance=~\"$libp2p_peers_top5\"}",
     "legendFormat": "{{instance}} [Top]"
    },
    {
     "expr": "libp2p_peers{instance=~\"$libp2p_peers_bottom5\"}",
     "legendFormat": "{{instance}} [Bottom]"
    }
   ]
  },
  {
   "title": "Libp2p Open Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_open_streams{instance=~\"$libp2p_open_streams_top5\"}",
     "legendFormat": "{{instance}}-{{type}}-{{dir}}-Top"
    },
    {
     "expr": "libp2p_open_streams{instance=~\"$libp2p_open_streams_bottom5\"}",
     "legendFormat": "{{instance}}-{{type}}-{{dir}}-Bottom"
    }
   ]
  },
  {
   "title": "libp2p traffic - In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\", instance=~\"$libp2p_traffic_in_top5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-in [Top]"
    },
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\", instance=~\"$libp2p_traffic_in_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-in [Bottom]"
    }
   ]
  },
  {
   "title": "libp2p traffic - Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\", instance=~\"$libp2p_traffic_out_top5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-in [Top]"
    },
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\", instance=~\"$libp2p_traffic_out_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-in [Bottom]"
    }
   ]
  },
  {
   "title": "Waku Discv5 In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(discv5_network_bytes_total{direction=\"in\", instance=~\"$discv5_in_top5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}} [Top]"
    },
    {
     "expr": "rate(discv5_network_bytes_total{direction=\"in\", instance=~\"$discv5_in_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}} [Bottom]"
    }
   ]
  },
  {
   "title": "Waku Discv5 Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(discv5_network_bytes_total{direction=\"out\", instance=~\"$discv5_out_top5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}} [Top]"
    },
    {
     "expr": "rate(discv5_network_bytes_total{direction=\"out\", instance=~\"$discv5_out_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}} [Bottom]"
    }
   ]
  },
  {
   "title": "libp2p low peers topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (libp2p_gossipsub_low_peers_topics)",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "libp2p high peers topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (libp2p_gossipsub_healthy_peers_topics)",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Nim GC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{instance=~\"$nim_gc_mem_bytes_bottom5\"}",
     "legendFormat": "{{instance}}--Bottom5"
    },
    {
     "expr": "nim_gc_mem_bytes{instance=~\"$nim_gc_mem_bytes_top5\"}",
     "legendFormat": "{{instance}}--Top5"
    }
   ]
  },
  {
   "title": "Container RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"zerotesting\", pod=~\"$container_memory_usage_bytes_top5\"}",
     "legendFormat": "{{pod}}-{{node}}-Top5"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"zerotesting\", pod=~\"$container_memory_usage_bytes_bottom5\"}",
     "legendFormat": "{{pod}}-{{node}}-Bottom5"
    }
   ]
  },
  {
   "title": "Received Bandwidth (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_receive_top5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}}-Top"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_receive_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}} (Bottom)"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_transmit_top5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}}-Top"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"zerotesting\", pod=~\"$container_network_transmit_bottom5\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{node}}-Bottom"
    }
   ]
  },
  {
   "title": "Waku Discv5 In - wip",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(rate(discv5_network_bytes_total{direction=\"in\"}[5m])[$__range:])\n)\n/\nsum by () (\n  avg_over_time(rate(discv5_network_bytes_total{direction=\"in\"}[5m])[$__range:])\n)\n* 100",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  },
  {
   "title": "Waku Discv5 Out - wip",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(rate(discv5_network_bytes_total{direction=\"out\"}[5m])[$__range:])\n)\n/\nsum by () (\n  avg_over_time(rate(discv5_network_bytes_total{direction=\"out\"}[5m])[$__range:])\n)\n* 100",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  },
  {
   "title": "Total Waku Discv5 Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(discv5_network_bytes_total[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(discv5_network_bytes_total{direction=\"in\", instance=~\"nodes-.*\"}[$__rate_interval]))",
     "legendFormat": "nodes - [In]"
    },
    {
     "expr": "sum(rate(discv5_network_bytes_total{direction=\"out\", instance=~\"nodes-.*\"}[$__rate_interval]))",
     "legendFormat": "nodes [Out]"
    }
   ]
  },
  {
   "title": "wip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(discovery_message_requests_outgoing_total{instance!~\"bootstrap-.*\"}))[$__rate_interval]-rate(sum(discovery_message_requests_incoming_total{instance!~\"bootstrap-.*\"}))[$__rate_interval]",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sum(discovery_message_requests_outgoing_total))[$__rate_interval]-rate(sum(discovery_message_requests_incoming_total))[$__rate_interval]",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sum(discovery_message_requests_outgoing_total{instance=~\"bootstrap-.*\"}))[$__rate_interval]-rate(sum(discovery_message_requests_incoming_total{instance=~\"bootstrap-.*\"}))[$__rate_interval]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "discv5 discover",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(waku_discv5_discovered{instance=~\"$top_discv5_discovered\", instance!~\"bootstrap-.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(waku_discv5_discovered{instance=~\"$bottom_discv5_discovered\", instance!~\"bootstrap-.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}