apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-servers-host
  labels: { network: host }
spec:
  selector:
    matchLabels: { app: iperf-hostnetwork }
  template:
    metadata:
      labels: { app: iperf-hostnetwork }
    spec:
      hostNetwork: true
      containers:
      - name: iperf
        image: networkstatic/iperf3:latest
        args: ['-s', '-p', '5201']